name: Welcome New Contributors

on:
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Check if this is a first-time contributor
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            👋 Welcome to the project!  
            Thank you for opening your first pull request. We appreciate your contribution.  
            Please make sure to follow our contribution guidelines. 🚀
